struct Person {

    function construct(name, surname, age) {
        self.name = name;
        self.surname = surname;
        self.age = age;
    }

    // call a method to get fullname
    function full_name() {
        return self.name + " " + self.surname;
    }

    // call the static function and use a name and a surname
    static function anyname(name, surname) {
        return name + " " + surname;
    }

    // or the block can initialize an instance variable
    // and call the method
    self.fullname = self.full_name();

}

person = new Person("Altun", "Hasanli", 17);
print(person.type);
print(person.fullname);
print(person.full_name());
print(Person.anyname(person.name, person.surname));
